package com.project.BuyRequestService.Entity;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.project.BuyRequestService.Entity.RequestEntity.RequestStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;

//@Getter @Setter
//@AllArgsConstructor
//@NoArgsConstructor
@Data // Lombok generates getters, setters, toString, equals, hashcode
@Entity
@Table(name="buy_request_details")
public class RequestEntity {

	// Auto-generating ID for RequestEntity
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long requestId;

	// Car ID column
	@Column(nullable = false)
	private Long carId;

	// User ID column
	@Column(nullable = false)
	private Long userId;

	// Request date column
	@Column(nullable = false)
	private LocalDate requestDate;

	// Request status using Enum
	@Enumerated(EnumType.STRING)
	// You can uncomment the @JsonIgnore annotation if you want to exclude the status field from JSON serialization
	// @JsonIgnore
	private RequestStatus status = RequestStatus.PENDING;

	// Enum to define different statuses of the request
	public enum RequestStatus {
		PENDING, ACCEPTING, REJECTED
	}

	// Getters and Setters will be automatically generated by Lombok (@Data annotation)
	// If Lombok doesn't work, you can uncomment and manually create getters and setters like below:

    public Long getRequestId() {
        return requestId;
    }

    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    public Long getCarId() {
        return carId;
    }

    public void setCarId(Long carId) {
        this.carId = carId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public LocalDate getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(LocalDate requestDate) {
        this.requestDate = requestDate;
    }

    public RequestStatus getStatus() {
        return status;
    }

    public void setStatus(RequestStatus status) {
        this.status = status;
    }
}
